apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-dotnet-crm-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-dotnet-crm-poc
  template:
    metadata:
      labels:
        app: random-dotnet-crm-poc
    spec:
      containers:
        - name: app
          image: nikoogle/test-dotnet-app-public:latest-slim
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false #Unfortunately the dotnet core image is too "Set" to run as root, from the base. Optimizing this will be out of scope, but this is a very critical thing.
            runAsUser: 1001
            runAsGroup: 2000
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          env:
            - name: DOTNET_USE_POLLING_FILE_WATCHER
              value: "true"
          resources:
            limits:
              cpu: 0.5
              memory: 2Gi
            requests:
              cpu: 0.25
          livenessProbe:
            httpGet:
              path: /api/weather
              port: 80
