apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-dotnet-crm-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: random-dotnet-crm-poc
  template:
    metadata:
      labels:
        app: random-dotnet-crm-poc
    spec:
      containers:
        - name: app
          image: nstankovbg/random-dotnet-crm-poc:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
          resources:
            limits:
              cpu: 0.5
            requests:
              cpu: 0.25
          livenessProbe:
            httpGet:
              path: /api/weather
              port: 80
