apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.network/random-dotnet-crm-poc-default: "true"
    io.kompose.service: app
  name: app
spec:
  containers:
    - image: nikoogle/test-dotnet-app-public:latest
      name: app
      ports:
        - containerPort: 80
      resources: {}
  restartPolicy: OnFailure
status: {}
