version: "3.9"

services:
  app:
    image: nikoogle/test-dotnet-app-public:latest-slim
    platform: linux/amd64
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "80:80"
