version: "3.9"

services:
  app:
    image: nikoogle/test-dotnet-app-public:latest
    platform: linux/arm64
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "8085:80"
    # user: "1001"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M
      labels:
        kompose.service.type: clusterip
        kompose.service.expose: "testdotnet.nstankov.com"
        kompose.service.group: app
