version: "3.9"

services:
  app:
    image: nikoogle/test-dotnet-app-public:latest
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 10
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M
      labels:
        kompose.service.type: nodeport
        kompose.service.expose: "testdotnet.nstankov.com"
        kompose.service.group: app
